//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtelierAvenue.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListingPicture
    {
        public int ListingPictureID { get; set; }
        public Nullable<int> ListingID { get; set; }
    
        public virtual ProductListing ProductListing { get; set; }
        public virtual ServiceListing ServiceListing { get; set; }
    }
}
