//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtelierAvenue.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderReturn
    {
        public int OrderReturnID { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.DateTime> RecieveDate { get; set; }
    
        public virtual OrderReturn OrderReturn1 { get; set; }
        public virtual OrderReturn OrderReturn2 { get; set; }
    }
}
