//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtelierAvenue.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductOrderLines = new HashSet<ProductOrderLine>();
            this.ProductPictures = new HashSet<ProductPicture>();
            this.Clients = new HashSet<Client>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public int ProductTypeID { get; set; }
        public int MaterialID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> PriceID { get; set; }
        public Nullable<decimal> ComissionPrice { get; set; }
        public int ProductStatusID { get; set; }
        public Nullable<int> WishlListCount { get; set; }
        public Nullable<int> ProductColorID { get; set; }
        public Nullable<int> ProductSizeID { get; set; }
    
        public virtual Price Price { get; set; }
        public virtual ProductSize ProductSize { get; set; }
        public virtual ProductColor ProductColor { get; set; }
        public virtual ProductMaterial ProductMaterial { get; set; }
        public virtual ProductStatu ProductStatu { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductOrderLine> ProductOrderLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductPicture> ProductPictures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients { get; set; }
    }
}
