//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtelierAvenue.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnLine
    {
        public int ProductID { get; set; }
        public int OrderReturnID { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual ReturnLine ReturnLine1 { get; set; }
        public virtual ReturnLine ReturnLine2 { get; set; }
    }
}
