//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtelierAvenue.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceListing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceListing()
        {
            this.ListingPictures = new HashSet<ListingPicture>();
        }
    
        public int ServiceListingID { get; set; }
        public int ClientID { get; set; }
        public Nullable<int> ServiceListingTypeID { get; set; }
        public Nullable<System.DateTime> ServiceListingDate { get; set; }
        public Nullable<int> ServiceListingStatusID { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListingPicture> ListingPictures { get; set; }
        public virtual ListingStatu ListingStatu { get; set; }
    }
}
