//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtelierAvenue.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAT
    {
        public int VATID { get; set; }
        public Nullable<int> VATPercentage { get; set; }
        public Nullable<System.DateTime> InitiationDate { get; set; }
    }
}
